name: Ubuntu CI

on: [push, pull_request]

jobs:
  focal-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Focal CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Compile and test
        uses: ./.github/actions/bazel-ci-focal
        with:
          bazel-args: //...

  bionic-ci:
    runs-on: ubuntu-latest
    name: Ubuntu BionicCI
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Compile and test
        uses: ./.github/actions/bazel-ci-bionic
        with:
          bazel-args: //...

