name: Ubuntu CI

on: [push, pull_request]

jobs:
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Compile and test
        uses: ./.github/actions/bazel-ci-jammy
        with:
          bazel-args: //...
