name: Ubuntu CI

on: [push, pull_request]

jobs:
  jammy-ci:
    runs-on: ubuntu-latest
    name: Ubuntu Jammy CI
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache bazel
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache-3
        with:
          path: |
            ${{ github.workspace }}/bazel_cache
          key: cache-bazel-${{ hashFiles('example/bazel.repos') }}
          restore-keys: |
              cache-bazel-${{ hashFiles('example/bazel.repos') }}
              cache-bazel-

      - name: Compile and test
        uses: ./.github/actions/bazel-ci-jammy
        with:
          bazel-args: //...

      - name: 'Upload Test Logs'
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: bazel-testlogs
          path: ${{ github.workspace }}/bazel-testlogs
          retention-days: 5
